services:
  backend:
    image: ghcr.io/mathisbruel/projet-etudes-2026-backend:latest
    ports:
      - "5001:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    restart: unless-stopped
